// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XMLAspNetCore.Models;

#nullable disable

namespace XMLAspNetCore.Migrations
{
    [DbContext(typeof(AdventureWorks2012Context))]
    [Migration("20230723123230_mssql.onprem_migration_192")]
    partial class mssqlonpremmigration192
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XMLAspNetCore.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductCategoryID")
                        .HasComment("Primary key for ProductCategory records.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"));

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Category description.");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.HasKey("ProductCategoryId")
                        .HasName("PK_ProductCategory_ProductCategoryID");

                    b.HasIndex(new[] { "Name" }, "AK_ProductCategory_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Rowguid" }, "AK_ProductCategory_rowguid")
                        .IsUnique();

                    b.ToTable("ProductCategory", "Production", t =>
                        {
                            t.HasComment("High-level product categorization.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
